### ISSUE TITLE
Что-то с форматированием опять не то

### ISSUE THREAD

**Issue by viki-reactor** [moonspwll/todo#2]
Код прилип к левому краю

https://github.com/moonspwll/todo/blob/b64ff30945197b37e8707a88f65c99d558292fed/js/index.js#L14-L60

Разметка уехала непонятно куда

https://github.com/moonspwll/todo/blob/b64ff30945197b37e8707a88f65c99d558292fed/js/index.js#L119-L131
https://github.com/moonspwll/todo/blob/b64ff30945197b37e8707a88f65c99d558292fed/js/index.js#L141-L153

**Comment by moonspwll** [comment]
@viki-reactor правки внесены, можно проверять :)

**Comment by viki-reactor** [comment]
Done
