### ISSUE TITLE
Бессмысленная проверка

### ISSUE THREAD

**Issue by viki-reactor** [moonspwll/todo#3]
https://github.com/moonspwll/todo/blob/0efcd87957c8f6c4918c9da2a01b00cbe1d25a91/js/index.js#L32

В проверке input.value.length > 0 нет смысла

Докажем это на примере 3 возможных вариантов ввода пользователем данных в инпут:

1. Не введено ничего (невалидно)
```
// значение пустая строка - ''

input.value.length > 0 // false
input.value.trim() // ''
false && '' // false && false -> false
```
```
// Убираем первое выражение

input.value.trim() // '' -> false
```

2. Введены пробелы (невалидно)
```
// значение пробелы - '   '

input.value.length > 0 // true
input.value.trim() // ''
true && '' // true && false -> false
```
```
// Убираем первое выражение

input.value.trim() // '' -> false
```

3. Введено значение (валидно)
```
// значение строка - ' Лёшка'

input.value.length > 0 // true
input.value.trim() // 'Лёшка'
true && 'Лёшка' // true && true -> true
```
```
// Убираем первое выражение

input.value.trim() // 'Лёшка' -> true
```
Необходимо убрать лишнее выражение

**Comment by moonspwll** [comment]
@viki-reactor Действительно. Убрал проверку на длину

**Comment by viki-reactor** [comment]
@moonspwll Ты не безнадежен
