### ISSUE TITLE
Подумать над рефакторингом функции priorityName

### ISSUE THREAD

**Issue by viki-reactor** [moonspwll/todo#4]
https://github.com/moonspwll/todo/blob/0efcd87957c8f6c4918c9da2a01b00cbe1d25a91/js/index.js#L83-L101

Переписывать  или нет - дело твое. Я хочу лишь посоветовать как сделать лучшее и красивее

Попробуй переписать функцию с использованием объекта
Конструкция свитч выглядит громоздко, а пропуск оператора break в кейсе влечет за собой провал в следующий кейс

```
const PRIORITY_HIGHT = 1;
const PRIORITY_MID = 1;
const PRIORITY_LOW = 1;

const priorities = {
    [PRIORITY_HIGHT]: { },
    [PRIORITY_MID]: { },
    [PRIORITY_LOW]: { }
};

const priority = (value) => priorities[value] || priorities[PRIORITY_MID];
```

Вот как-то так
Получше смотрится чем свитч, не правда ли?
Да вообще пиздато смотрится

**Comment by moonspwll** [comment]
@viki-reactor переписал

**Comment by viki-reactor** [comment]
@moonspwll Сойдет
